version: '3'
services:
  database:
    image: mariadb:${DB_VERSION:-10.3}
    volumes:
      - "./.docker/data/db:/var/lib/mysql"
      - "./.docker/config/db:/etc/mysql/conf.d"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USER:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    restart: always
    command:
      'mysqld --innodb-flush-method=fsync'
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    restart: always
  php:
    image: peterbooker/phplaravel:7.3-fpm
    depends_on:
      - database
      - redis
    working_dir: /var/www/html
    environment:
      APP_URL: ${DOMAIN:-localhost}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST:-database}
      DB_PORT: ${DB_PORT:-3306}
      DB_DATABASE: ${DB_DATABASE:-laravel}
      DB_USERNAME: ${DB_USER:-laravel}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_PORT: ${REDIS_PORT:-6379}
      MAIL_DRIVER: ${MAIL_DRIVER:-sendmail}
      MAIL_SENDMAIL: ${MAIL_SENDMAIL:-'/usr/sbin/sendmail -S mailhog:1025'}
    volumes:
      - "./.docker/config/php/php.ini:/usr/local/etc/php/php.ini"
      - "./.docker/html:/var/www/html"
      - "./.docker/adminer:/var/www/adminer"
    extra_hosts:
      - "localhost:172.18.0.1"
    restart: always
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
  caddy:
    image: abiosoft/caddy
    depends_on:
      - php
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    volumes:
      - "./.docker/config/caddy/Caddyfile:/etc/Caddyfile"
      - "./.docker/html:/var/www/html"
      - "./.docker/adminer:/var/www/adminer"
    ports:
      - "80:80"
      - "443:443"